mysql johnsmedley_ce < ./scripts/attributes.sql
mysql johnsmedley_ce < ./scripts/ee.sql
mysql johnsmedley_ce < ./scripts/cms.sql
mysql johnsmedley_ce < ./scripts/catalogrule.sql
mysql johnsmedley_ce < ./scripts/salesrule.sql
mysql johnsmedley_ce < ./scripts/category.sql
mysql johnsmedley_ce < ./scripts/product.sql
mysql johnsmedley_ce < ./scripts/cataloginventory.sql
mysql johnsmedley_ce < ./scripts/customer.sql
mysql johnsmedley_ce < ./scripts/quote.sql
mysql johnsmedley_ce < ./scripts/sales.sql
mysql johnsmedley_ce < ./scripts/wishlist.sql
