SET FOREIGN_KEY_CHECKS=0;
TRUNCATE wishlist;
TRUNCATE email_wishlist;
ALTER TABLE `wishlist`
    DROP COLUMN `name`,
    DROP COLUMN `visibility`,
    DROP KEY `WISHLIST_CUSTOMER_ID`,
    ADD UNIQUE KEY `WISHLIST_CUSTOMER_ID` (`customer_id`);
ALTER TABLE `wishlist_item_option`
    DROP KEY `WISHLIST_ITEM_OPTION_PRODUCT_ID_SEQUENCE_PRODUCT_SEQUENCE_VALUE`,
    ADD KEY `WISHLIST_ITEM_OPTION_PRODUCT_ID_CATALOG_PRODUCT_ENTITY_ENTITY_ID` (`product_id`);
SET FOREIGN_KEY_CHECKS=1;